src/objects/Actor__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Actor Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Actor</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Actor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActorInFilm__c.object
<CustomObject>
    <fields>
        <fullName>Actor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actor</label>
        <referenceTo>Actor__c</referenceTo>
        <relationshipLabel>ActorInFilms</relationshipLabel>
        <relationshipName>ActorInFilms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Film__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Film</label>
        <referenceTo>Film__c</referenceTo>
        <relationshipLabel>ActorInFilms</relationshipLabel>
        <relationshipName>ActorInFilms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ActorInFilm</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>ActorInFilm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ActorInFilms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Film__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <externalId>true</externalId>
        <label>Film Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Film</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Film Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Films</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FilmLibraryController.cls
/**
 * Created by alaputsky on 9/16/2019.
 */

public with sharing class FilmLibraryController {    

    @AuraEnabled
    public static List<Film__c> getFilms() {
        List<Film__c> films = [
                SELECT Id, Name__c, (SELECT Actor__r.Name__c FROM ActorInFilms__r)
                FROM Film__c
                ORDER BY Name__c ASC 
        ];

        return films;
    }

    @AuraEnabled
    public static List<Film__c> searchFilmByNameBack(String nameSegment) {
        String nameSegmentSoql = '%' + nameSegment + '%';
        List<ActorInFilm__c> actors = [
                SELECT Id, Actor__r.Name__c, Film__r.Id
                FROM ActorInFilm__c
                WHERE Actor__r.Name__c LIKE :nameSegmentSoql
        ];

        List<Id> filmIds = new List<Id>();
        for (ActorInFilm__c act : actors) {
            filmIds.add(act.Film__r.Id);
        }

        List<Film__c> films = [
                SELECT Id, Name__c, (SELECT Actor__r.Name__c FROM ActorInFilms__r)
                FROM Film__c
                WHERE Id = :filmIds
        ];

        return films;
    }

    @AuraEnabled
    public static List<String> getActors() {
        List<Actor__c> actors = [
                SELECT Id, Name__c
                FROM Actor__c
        ];

        List<String> actorNames = new List<String>();
        for (Actor__c act : actors) {
            actorNames.add(act.Name__c);
        }

        return actorNames;
    }
}